name: Python CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'python/**'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements/dev.txt
      - name: Run ruff
        run: ruff check src
      - name: Run mypy
        run: mypy src

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -r requirements/dev.txt
      - name: Run tests with coverage
        run: |
          coverage run -m pytest -svv
          coverage report
